### ISSUE TITLE
[Fatal] Vidsrc-search terminating with exit code 1

### ISSUE THREAD

**Issue by sugizo** [SomedudeX/vidsrc-search#1]
**execute**
`!vidsrc-search libary download`

**result**
```
 [Fatal] Invalid argument: libary
 [Fatal] Vidsrc-search terminating with exit code 1
```

best regards

**Comment by SomedudeX** [comment]
This is a typo in the help message where `library` has been spelled as `library`. It has been fixed in the latest patch. 

You can update vidsrc-search by running `pip install --upgrade vidsrc-search`.
